### ISSUE TITLE
About matching to the same point

### ISSUE THREAD

**Issue by shamangary** [cavalli1234/AdaLAM#1]
Hello @cavalli1234, thank you for the great work.
I am trying the provided code, brilliant btw, but it looks like the matching could match to the same point right?

The following list is the matches generated from my test. 
```
# testing
adamatcher = AdalamFilter()
adamatcher.config['scale_rate_threshold'] = None
adamatcher.config['orientation_difference_threshold'] = None
adamatcher.config['area_ratio'] = 10
adamatcher.config['search_expansion'] = 10

matches = adamatcher.match_and_filter(kpA, kpB, descA, descB, im1shape=None, im2shape=None, o1=None, o2=None, s1=None, s2=None).cpu().numpy()
 
# matches
[ 19 359]
 [ 23 429]
 [ 24 413]
 [ 53 389]
 [ 54 382]
 [ 55 385]
 [ 74 503]
 [ 84 403]
 [ 95 465]
 [ 99 526]
 [115 543] <---
 [118 490]
 [119 543] <---
 [124 543] <---
 [137 465]
 [147 420]
 [152 589]
 [153 495]
 [172 589]
```

Is this an expected feature? Thank you

**Comment by cavalli1234** [comment]
Hello @shamangary, thank you!

Yes this is possible, especially if multiple matches appear to be consistent with different overlapping local neighborhoods. Indeed, the particular configuration in this example uses very large neighborhood sizes which mostly overlap. 

Allowing multiple converging correspondences can be a useful feature for example in the case of repeated structures, where AdaLAM being a local verification method cannot disambiguate clearly which is the correct match. 

Generally a global verification method like a RANSAC should be able to disambiguate these cases.

**Comment by shamangary** [comment]
Thank you. Beautiful code :)
