### ISSUE TITLE
AdaLAM to kornia?

### ISSUE THREAD

**Issue by ducha-aiki** [cavalli1234/AdaLAM#11]
Hi,

Would you be interested in the AdaLAM integration into kornia? We are now developing local features module and AdaLAM would be a great fit. 
It would also boost usage and citation of AdaLAM :)

--
Best, Dmytro.

**Comment by ducha-aiki** [comment]
https://github.com/kornia/kornia/pull/1831 :)

**Comment by cavalli1234** [comment]
This is absolutely great, thanks a lot @ducha-aiki :)
