### ISSUE TITLE
use ratio test when no correspondences survive

### ISSUE THREAD

**Issue by vdvchen** [cavalli1234/AdaLAM#2]
Hi, thank you for your great work.

While testing the code, I find there are some cases where no correspondences survive after filtering. May be ratio test could be adopted in this situation to be a remedy.

**Comment by cavalli1234** [comment]
Hi, thank you for your observation, 

indeed it may happen that no matches are found and a backup strategy becomes useful. I already experimented with applying ratio test when adalam fails, but generally this helps very marginally as it always triggers on quite difficult cases where also ratio test fails (or on non-matching pairs where you do not want matches at all) 

However, I agree that this may be a possibility that one wants to test out, I will add it as an option as soon as I have the time!

**Comment by cavalli1234** [comment]
Closing for now, feel free to re-open!
