### ISSUE TITLE
it seems that the program cannot run successfully.

### ISSUE THREAD

**Issue by ahong007007** [cavalli1234/AdaLAM#3]
When the program example.py is executed, an error is reported, and it seems that the program cannot run successfully.

![image](https://user-images.githubusercontent.com/22077027/89604729-735b0a00-d89e-11ea-8ddd-437ae0d7fbf1.png)

**Comment by cavalli1234** [comment]
Hi,

I suspect this issue comes from an old pytorch version with a different interface to the function where. Which is your pytorch version? Could you try upgrading to the latest?

**Comment by wangjialuu** [comment]
Same problem using pytorch == 1.0.1

**Comment by cavalli1234** [comment]
Yes I can confirm that this is an issue with the where function from older pytorch versions. According to the pytorch documentation the torch.where(condition) has been introduced only with pytorch 1.2.0. I cannot exclude that there might be further compatibility issues even after fixing this.

The older version of where performs a fundamentally different functionality, so trying to support older versions of pytorch would imply quite a complete refactoring in the way indices are managed in the core of AdaLAM.

The current implementation is tested only under the environment specified with adalam.yml, but it's still good to know some lower bounds in versions of the packages in use.

For now I am closing the issue, feel free to re-open for further discussion!
