### ISSUE TITLE
Creating a colmap dataset

### ISSUE THREAD

**Issue by Zumbalamambo** [cavalli1234/AdaLAM#6]
How do I create a colmap dataset with custom dataset?

**Comment by cavalli1234** [comment]
Hi @Zumbalamambo,

I am not sure I completely got your question. You can make many customizations with colmap.

If you wish to use custom keypoints/descriptors on you images you should fill in the relative database tables before running the rest of the reconstruction. There are several helper scripts to make this easier to implement. Please refer to the original colmap repository for detailed instructions.

If you wish to use AdaLAM matches with standard SIFT, you can use the script in the examples directory of this repository. If you call it without arguments or just open it you should be able to read its usage instructions. If you need to import your custom matches inside colmap, the same script is an example on how to do it.

Let me know if I answered your question!

**Comment by cavalli1234** [comment]
Closing for now, feel free to re-open!
