### ISSUE TITLE
setup env for cpu 

### ISSUE THREAD

**Issue by haihengcao** [cavalli1234/AdaLAM#7]
we have a mac, how to setup env for cpu?  Any help would be appreciated.

**Comment by cavalli1234** [comment]
Hi @haihengcao,

I did not run experiments on mac, but this should not be an issue!
For setting up the environment for CPU, it should be enough to setup a standard python 3.7 environment with tqdm, numpy, Pytorch CPU 1.3 or newer available.

However, note that AdaLAM is designed and optimized for GPU, so runtimes could not be optimal.

Let me know if this works for you!

**Comment by haihengcao** [comment]
Thanks for your reply. We run some experiments on linux gpu server using cuda on a image set containing  thounds of images. we found the following things:
a. colmap match + colmap two_view_geometry cost about 30 minutes. and adalam match_and_filter cost about 3 hours.  we wonder is it normal, or why the adalam run much slower than colmap. 

b.cpu ratio keeps 800% on 8 core cpu while running. is it because tensor in torch spawning threads underhood? 

Thanks again and look forward your kindly replying.

**Comment by cavalli1234** [comment]
Thank you for your experiments!
It is indeed expected that AdaLAM takes more than the standard colmap matching scheme, which also uses GPU at least for the matching step. However, I did not compare them directly and I am a bit surprised that it ends up being 6 times slower.

Instead, high CPU usage is not expected, as the current implementation is completely based on pytorch and never explicitly switches to CPU when cuda is available. I assume some minor operations may still be executed on the CPU even for cuda ops, but I would not expect a major workload. Numpy ops are very limited, and mostly happen to format data from reading a colmap database.

Could you check the GPU usage and that cuda is actually visible for pytorch in the environment used?

Thank you again!

**Comment by cavalli1234** [comment]
Closing for now, feel free to re-open!
